### ISSUE TITLE
installer fails on pre Pi 2 CPUs or Pi 4 (anything NOT ARM v7)

### ISSUE THREAD

**Issue by tomperrine** [dinofizz/picluster-ansible#1]
I have a mixed cluster with several different kinds of Pi. I found that your code specifically pulls the ARM v7 versions of some tools, which work on Pi2 or later, but not the Pi B.

I haven't checked Pi4 (ARM v8) as my Pi 4s are doing other things at the moment, but they should be OK.

If you want the simple changes, let me know - or just close this if you're not interested.

**Comment by dinofizz** [comment]
Hi Tom, thanks for the comment. 

For my own stack I'm using just Pi 4's, and have not put any effort into running the software on anything else. While the Pi 4 system on chip uses an ARM v8 architecture, it is compatible with ARM v7 software (v8 brings the address space from 32-bit to 64-bit).

The the default Raspbian image uses a 32-bit kernel, which is why I only need to specify and work with ARM v7 tools.

One can enable a 64-bit kernel via a config.txt change: 
https://www.raspberrypi.org/forums/viewtopic.php?t=250730#p1530551

I've not tested anything with the 64-bit kernel, I hope to soon though!
